org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official

admobAppId=ca-app-pub-5793073160443124~9119096012
bannerUnit=ca-app-pub-5793073160443124/2844408264
interstitialUnit=ca-app-pub-5793073160443124/4277832877
rewardedUnit=ca-app-pub-5793073160443124/8867814571
